using System.Collections.Generic;

namespace Convai.Domain.Identity
{
    /// <summary>
    ///     Provides an application-specific end user identifier for Convai connections.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         Implementations of this interface generate stable identifiers that allow the Convai server
    ///         to track end users across sessions. This enables features such as:
    ///     </para>
    ///     <list type="bullet">
    ///         <item>
    ///             <description>Stable end-user identity across sessions</description>
    ///         </item>
    ///         <item>
    ///             <description>Monthly Active User (MAU) tracking for billing</description>
    ///         </item>
    ///         <item>
    ///             <description>Cross-session conversation continuity</description>
    ///         </item>
    ///     </list>
    ///     <para>
    ///         <b>Important - Identity Flow:</b>
    ///     </para>
    ///     <para>
    ///         The <c>end_user_id</c> generated by this provider is sent to the server during connection.
    ///         The backend uses it as the stable client-owned identity for that user.
    ///     </para>
    ///     <para>
    ///         When memory is enabled for a character, the backend resolves this identifier to an internal
    ///         <c>speaker_id</c> and uses the storage key <c>speaker_id:character_id</c>.
    ///     </para>
    ///     <para>
    ///         The default implementation, <c>DeviceEndUserIdProvider</c>, uses the device's unique identifier
    ///         with a GUID fallback for platforms where device identification is unavailable.
    ///     </para>
    ///     <para>
    ///         Custom implementations can be registered in the runtime context/container to provide
    ///         application-specific user identification (e.g., based on authenticated user accounts).
    ///     </para>
    /// </remarks>
    public interface IEndUserIdProvider
    {
        /// <summary>
        ///     Generates or resolves the end user identifier that should be sent with Convai connect requests.
        /// </summary>
        /// <returns>
        ///     A stable end user identifier string. The identifier should be consistent across sessions
        ///     for the same end user to enable cross-session features.
        /// </returns>
        /// <remarks>
        ///     This value is sent to the server as <c>end_user_id</c> and should remain stable for the same
        ///     human user across sessions. The backend may resolve it to an internal <c>speaker_id</c>
        ///     for memory and persistence, but the SDK should treat <c>end_user_id</c> as the primary public identity.
        /// </remarks>
        public string GenerateEndUserId();
    }

    /// <summary>
    ///     Resolves the effective end-user identity for runtime Convai requests.
    /// </summary>
    public interface IEndUserIdentityProvider
    {
        /// <summary>
        ///     Gets the effective end-user identifier for the current runtime session.
        /// </summary>
        public string GetEndUserId();
    }

    /// <summary>
    ///     Resolves optional metadata for the effective end user of the current runtime session.
    /// </summary>
    public interface IEndUserMetadataProvider
    {
        /// <summary>
        ///     Gets optional metadata to send as <c>end_user_metadata</c> on connect.
        ///     Return <c>null</c> or an empty dictionary to omit metadata from the request.
        /// </summary>
        public IReadOnlyDictionary<string, object> GetEndUserMetadata();
    }

    /// <summary>
    ///     Runtime credentials required for Convai room/session requests.
    /// </summary>
    public readonly struct RuntimeCredentials
    {
        public RuntimeCredentials(string apiKey, string coreServerUrl)
        {
            ApiKey = apiKey ?? string.Empty;
            CoreServerUrl = coreServerUrl ?? string.Empty;
        }

        public string ApiKey { get; }
        public string CoreServerUrl { get; }
        public bool IsConfigured => !string.IsNullOrWhiteSpace(ApiKey) && !string.IsNullOrWhiteSpace(CoreServerUrl);
    }
}
