using System.Collections.Generic;
using Convai.Shared.Types;

namespace Convai.Infrastructure.Networking
{
    /// <summary>
    ///     Focused read-only view of transport configuration settings.
    ///     Extracted from <see cref="IConfigurationProvider" /> to separate
    ///     read-only config access from session-persistence mutations.
    /// </summary>
    public interface ITransportConfiguration
    {
        /// <summary>
        ///     Gets the API key for authenticating with the Convai service.
        /// </summary>
        public string ApiKey { get; }

        /// <summary>
        ///     Gets the base URL of the Convai core server (without endpoint path).
        ///     Example: "https://live.convai.com"
        /// </summary>
        public string CoreServerUrl { get; }

        /// <summary>
        ///     Gets the connection type for character sessions.
        /// </summary>
        public ConvaiConnectionType ConnectionType { get; }

        /// <summary>
        ///     Gets the video track name used for vision streaming.
        /// </summary>
        public string VideoTrackName { get; }

        /// <summary>
        ///     Gets the server endpoint for room connections.
        /// </summary>
        public ConvaiServerEndpoint ServerEndpoint { get; }

        /// <summary>
        ///     Gets the lip sync transport options negotiated for this room session.
        ///     Defaults to <see cref="LipSyncTransportOptions.Disabled" /> when no lip sync capability is present.
        /// </summary>
        public LipSyncTransportOptions LipSyncTransportOptions { get; }

        /// <summary>
        ///     Gets the end user identifier for cross-session tracking.
        /// </summary>
        /// <remarks>
        ///     This identifier enables stable end-user tracking, analytics, management, and memory lookup.
        ///     The value is typically generated by an <see cref="Convai.Domain.Identity.IEndUserIdProvider" /> implementation.
        /// </remarks>
        public string EndUserId { get; }

        /// <summary>
        ///     Gets optional metadata for the current end user.
        /// </summary>
        public IReadOnlyDictionary<string, object> EndUserMetadata { get; }

        /// <summary>
        ///     When true, the connect request sends debug=true so the backend enables RTVI metrics for this session.
        /// </summary>
        public bool Debug { get; }
    }

    /// <summary>
    ///     Additive credential metadata used by SDK-owned transport configurations without changing the public
    ///     <see cref="ITransportConfiguration" /> contract implemented by third parties.
    /// </summary>
    internal interface ITransportAuthenticationConfiguration
    {
        public bool UsesAuthToken { get; }
    }

    internal static class TransportAuthenticationSupport
    {
        internal const string ApiKeyHeaderName = "X-API-Key";
        internal const string AuthTokenHeaderName = "API-AUTH-TOKEN";

        internal static bool UsesAuthToken(ITransportConfiguration configuration) =>
            configuration is ITransportAuthenticationConfiguration { UsesAuthToken: true };

        internal static string GetHeaderName(ITransportConfiguration configuration) =>
            UsesAuthToken(configuration) ? AuthTokenHeaderName : ApiKeyHeaderName;
    }
}
